---
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce
    - python-pip

- name: Install docker-compose
  pip:
    name: docker-compose

- name: provide docker compose file
  template: src=compose_file.j2 dest=/home/vagrant/docker-compose.yml

- name: provide daemon.json file
  template: src=daemon_json.j2 dest=/etc/docker/daemon.json

- name: restart docker
  service:
    name: docker
    state: restarted

- name: shudown docker compose
  shell: docker-compose down

- name: run docker compose file
  shell: docker-compose up -d
